name: Check
on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix flake check
        run: nix flake check --all-systems

      - name: nixfmt
        run: nix develop --command bash -c 'find . -name "*.nix" | xargs nixfmt-rfc-style --check'

      - name: statix
        run: nix develop --command statix check .

      - name: deadnix
        run: nix develop --command deadnix --fail .

      - name: Build all machines
        run: |
          for drv in $(nix eval .#nixosConfigurations --apply 'x: builtins.attrNames x' --json | nix develop --command jq -r '.[]'); do
            echo "::group::Building $drv"
            nix build .#nixosConfigurations."$drv".config.system.build.toplevel --dry-run
            echo "::endgroup::"
          done
